# Generated by Django 3.0.6 on 2020-06-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_underage', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faces')),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_limit', models.IntegerField(blank=True, default=3600)),
                ('grace_time', models.IntegerField(default=0)),
                ('time_today', models.IntegerField(default=0)),
                ('week_time', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('time_exceeded', models.BooleanField(default=False)),
                ('forbidden', models.BooleanField(default=False)),
                ('warning', models.TextField(default='None')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='details.User')),
            ],
        ),
    ]
